language: objective-c
cache:
  directories:
    - node_modules
env:
  - NODE_VERSION="8.2.1"
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - node --version
install:
  - npm install
script:
  - npm test
before_deploy:
  - brew update
  - brew install wine
  - wine --version
  - brew install makensis
  - npm run archive
deploy:
  provider: releases
  api_key:
    secure: MHCmOHJnzVnKFLRCBmH2LflYFJFC7JbEfkcp8yCkrLqxFVIDGgEC9Z/L5URRClNN8bHirUkFshfJSNojsXMIaZ+9hzVwLzJmbeb9SLF4vYDjB5wGoY/7PoAFTCLLHtVHxVepKJGDVT+L/uHMJEEf5ZGe2N2abQGnDRKyqm6Gl5c5Entn3Dt1AXxM8DBBnbFjcaqy78BdGXTkdiV+urrLNvsc2SVrPujiRUB+a2Jw3kuucyPvbAISUa0z2BcQkTH0M8JChbePbbvcRhQfPJBOfNrUJSAtSxgyqbLaZp8pyOy95jn3Gtb295Dw10HDzLN9fdpz3rUF4XxCGL9k4LVYRb95snUFHxUgTVCAKgDqHm5ZM68z16T8Uy80li89fT6t8h7/sYt4/XREjps1idwy3cxpswKcEbYDd1aVZvM02guMPC0zQ7StisdQBLwa1/WmwSB/25aat6BsgNv0UmYi6NlEjtE4MUkaCXDPLqSh31WRHh2WffPPOFex21zVx4j9GlrMU64+P/WtrGzxtnJWMdC9t/hGJC8ZWDKUlbA6f1kFlpooCezMpsN4ZdJU2l3RRyZ9mg3LLQBIJMExNSd+MZKbmV/IeW5t+Mqlz3jG9wS0YfzFPP/PHqo3aSnj342ldDiRLIukW99vzGx10a3DFW7AqVlwioJY1FH2f1wyD9o=
  file:
    - dist/win32/YouTubeLiveSupport-win32.zip
    - dist/win64/YouTubeLiveSupport-win64.zip
  skip_cleanup: true
  on:
    repo: yuta0801/YouTubeLiveSupport
    tags: true
    all_branches: true
